name: InspireNL
favicon: null
layout_spectrum: 0.8439560630358756
typography_spectrum: 0.8292220453731716
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f89c1c'
    - '#009ada'
    - '#00ffff'
    - '#0000ff'
    - '#ff0000'
  brandStrength: 0.5
  lightness: 0.4508663534652442
  saturation: 0.48732928233221173
  rhythmicContrast: 0.9760419949889183
purpose: []
